### ISSUE TITLE
How to change the logo Kaltura after integrate with chrome cast?

### ISSUE THREAD

**Issue by hoanhnv** [kaltura/playkit-android#328] opened 2017-12-06 15:11 UTC
Hi Team,
How to change the logo Kaltura after integrate with chrome cast?
Pls support me or give me the document to integrate player with chrome cast.
Thanks!

**Comment by kaltura-hooks** [comment] 2017-12-06 15:38
Hi @hoanhnv,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by giladna** [comment] 2017-12-07 15:33
@hoanhnv 
where do you store your reciver id?

you put it on the URL

like this example:  http://192.168.193.60//html5.kaltura/mwEmbed/modules/Chromecast/resources/receiver/receiver.html?logoUrl="https://www.yourcompany.com/ChromeCast.jpg"

**Comment by kaltura-hooks** [comment] 2017-12-07 21:09
Hi @hoanhnv,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by ninobaldo** [comment] 2017-12-08 15:53
Hi @giladna 

I have a similar issue. For now I am using the  application id from [playkit android sample](https://github.com/kaltura/playkit-android-samples) 

```java
CastOptions.Builder()
                .setReceiverApplicationId(context.getString(R.string.cast_app_id))
                .setCastMediaOptions(mediaOptions)
                .build();
```
But if a set another app id (I created a application on Google Cast SDK Developer Console) the player don't stream. There is no error message or nothing, just don't work ):

The problem is if I don't change the app id I can't change the splash screen when app start streaming the video ([styled receiver](https://developers.google.com/cast/docs/styled_receiver)). Can I?

Do you have any procedure, documentation, or tutorial to implement this?

**Comment by giladna** [comment] 2017-12-09 20:22
@ninobaldo 

what is the URL you use in your receiver id?
what is your partner Id?

**Comment by ninobaldo** [comment] 2017-12-10 01:34
Hi,

Partner id: 2267831
Receiver URL: https://watch.tv.br/css/chromecast/watchtvskin.css <https://watch.tv.br/css/chromecast/watchtvskin.css>

**Comment by giladna** [comment] 2017-12-10 08:19
hi 
I can see that your partner is using 2.63.3

so I recommand to use that url as your receiver URL
https://cdnapisec.kaltura.com/html5/html5lib/v2.63.3/modules/Chromecast/resources/receiver/receiver.html

if you wantto add your logo just add this queryparam to that url

?logoUrl="https://www.yourcompany.com/ChromeCast.jpg"

**Comment by ninobaldo** [comment] 2017-12-11 12:33
Tks, I will try it!

**Comment by ninobaldo** [comment] 2017-12-11 17:00
@giladna I was trying use a *appID* from *Google Cast SDK Developer Console*, but if you don't support external receiver. Where I set that url?



```java
ConverterOvpCast converterOvpCast = new ConverterOvpCast(
                    ConverterGoogleCast.ReceiverEnvironmentType.RECEIVER_OVP_ENVIRONMENT,
                    "",
                    Globals.kalturaid.toString(),
                    "https://pubads.g.doubleclick.net/....",
                    "https://cdnapisec.kaltura.com/html5/html5lib/v2.63.3/modules/Chromecast/resources/receiver/receiver.html?logoUrl=\"https://watch.tv.br/css/chromecast/logo.png\"", //mwEmbed
                    "2267831",
                    "<uiconfigId>",
                    converterMediaMetadata);
```

Here?

**Comment by giladna** [comment] 2017-12-12 07:11
@ninobaldo 
in your Google Cast SDK Developer Console edit YOUR reciver id with 
https://cdnapisec.kaltura.com/html5/html5lib/v2.63.3/modules/Chromecast/resources/receiver/receiver.html?logoUrl="https://watch.tv.br/css/chromecast/logo.png"

You can try the Reciver I created on my side for your use :  DF9EC950

 the line in the code for mwEmbed can be replaced with "" is is only if you want to override the one that in the receiver 

please update if it works with the given reveiver id / your own

**Closed** 2017-12-13 07:24 UTC
Labels: question
